printWidth: 80
tabWidth: 2
useTabs: false

semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false

trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always

proseWrap: always
htmlWhitespaceSensitivity: ignore

endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
